### ISSUE TITLE
May I ask if it can be used for section v2board

### ISSUE THREAD

**Issue by liummingyuan** [Github-Aiko/Aiko-Server#43]
May I ask if it can be used for section v2board

**Comment by Github-Aiko** [comment]
Yes , but wait next version , i will support v2b

**Comment by liummingyuan** [comment]
Great!!!

**Comment by purelolly** [comment]
> Yes , but wait next version , i will support v2b

Will the next version support Hysteria in v2board?

**Comment by Github-Aiko** [comment]
Yes

**Comment by Github-Aiko** [comment]
If there is a problem please create a new issue
